version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_DSN=mysql_user:mysql_password@tcp(db:3306)/bookstore?charset=utf8mb4&parseTime=True&loc=Local

  db:
    image: mysql:latest
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: bookstore
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
